stages:
  - wechatSDKJob
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GITLAB_VERSION: $GITLAB_VERSION
  BUILD_OTHER_PROJECTS: $BUILD_OTHER_PROJECTS
  GITLAB_BUILD_DEPLOY: $GITLAB_BUILD_DEPLOY
  GITLAB_BUILD: $GITLAB_BUILD
  GITLAB_BUILD_ISSTATIC: $GITLAB_BUILD_ISSTATIC
  GITLAB_UPLOAD_FRAMEWORK: $GITLAB_UPLOAD_FRAMEWORK

wechatSDKJob:
  stage: wechatSDKJob
  script:
    # 编译
    - echo $gitlab_uploadToGit
    - sh bundle.sh $GITLAB_VERSION $CI_COMMIT_REF_NAME $GITLAB_BUILD_ISSTATIC $GITLAB_BUILD_DEPLOY $GITLAB_UPLOAD_FRAMEWORK
  tags:
    - mac-studio
  rules:
    - if: '$BUILD_OTHER_PROJECTS != "true"'
      when: never
    - if: '$BUILD_OTHER_PROJECTS == "true"'
      when: delayed
      start_in: '2'
    - when: on_success

