# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# SCP上传重试脚本路径
SCP_RETRY_SCRIPT = "../../FinClipSDK-iOS/scp_with_retry.sh"

def handleSPM(zip_path, version)
  checksum = sh("swift package compute-checksum #{zip_path}").strip
  
  # 定义基础路径
  base_path = "../../ext_spm/FinAppletWXExt"
  
  # 确保目标目录存在
  sh("mkdir -p #{base_path}")
  
  # 读取模板文件
  template_content = File.read("../Package.tpl.swift")
  
  # 替换占位符
  package_content = template_content
    .gsub("___CHECKSUM_PLACEHOLDER___", checksum)
    .gsub("___VERSION_PLACEHOLDER___", version)
  
  # 写入到目标文件
  File.write("#{base_path}/Package.swift", package_content)
  
  puts "SPM Package.swift generated with checksum: #{checksum}"
  
  # 生成 spm.json 文件
  spm_json_content = <<~JSON
    {
      "version": "#{version}",
      "url": "ssh://gitlab.finogeeks.club/finclip-ios/spm/FinAppletWXExt.git",
      "publicUrl": "https://mac-studio@git.finogeeks.com/spm/FinAppletWXExt.git"
    }
  JSON
  
  File.write("#{base_path}/spm.json", spm_json_content)
  puts "SPM spm.json generated with version: #{version}"
end

platform :ios do
  desc "Description of what the lane does"
  before_all do |lane, options|
    sh("rm", "-rf", "../build")
    sh("rm", "-rf", "../dist")
    cocoapods(
      clean: true,
      podfile: "./Podfile"
    )
  end

  lane :deploy do
    
    # version = sh("git describe --abbrev=0 --tags | tr -d '\\n' | tr -d '\\t'")
    version = ENV["version"]
    isUploadScp = ENV['isUploadScp']


    # 增加build版本号
    #increment_build_number
    set_info_plist_value(path: './FinAppletWXExt/Info.plist', key: 'CFBundleShortVersionString', value: "#{version}")
    
    # 编译代码
    xcodebuild(
      workspace: "FinAppletWXExt.xcworkspace",
      scheme: "FinAppletWXExt",
      xcargs: "-sdk iphoneos",
      configuration: "Release",
      clean: true,
      derivedDataPath: "./build",
      build: true
    )
    sh("mkdir -p ../dist/Release")
    sh("cp","-r", "../build/Build/Products/Release-iphoneos/FinAppletWXExt.framework", "../dist/Release/FinAppletWXExt.framework")

    zip(
      path: "dist/Release/FinAppletWXExt.framework",
      output_path: "dist/FinAppletWXExt-Min-#{version}.zip"
    )

    # zipFileName ="FinAppletWXExt-Min-#{version}.zip"
    # path=Dir.pwd
    # sh("coscli cp #{path}/../dist/#{zipFileName} cos://static-1251849568/finchat/sdk/#{zipFileName} --meta=x-cos-meta-build-type:release")
  
    # scp(
    #   host: "192.168.0.35",
    #   username: "finchat",
    #   password: "abcd@@123",
    #   upload: {
    #     src: "dist/FinAppletWXExt-Min-#{version}.zip",
    #     dst: "/data/ci/app/html/finchat/sdk"
    #   }
    # )
    # 原命令保留注释
    # sh("sshpass -p 'abcd@@123' scp ../dist/FinAppletWXExt-Min-#{version}.zip finchat@192.168.0.35:/data/ci/app/html/finchat/sdk")
    # 使用重试脚本上传
    sh("#{SCP_RETRY_SCRIPT} ../dist/FinAppletWXExt-Min-#{version}.zip finchat@192.168.0.35:/data/ci/app/html/finchat/sdk")

    xcodebuild(
      workspace: "FinAppletWXExt.xcworkspace",
      scheme: "FinAppletWXExt",
      xcargs: "-sdk iphonesimulator -arch arm64 -arch x86_64",
      configuration: "Release",
      clean: true,
      derivedDataPath: "./build",
      build: true
    )

    sh("xcodebuild -create-xcframework -framework ../dist/Release/FinAppletWXExt.framework -framework ../build/Build/Products/Release-iphonesimulator/FinAppletWXExt.framework -output ../dist/Release/FinAppletWXExt.xcframework")

    zip(
      path: "dist/Release/FinAppletWXExt.xcframework",
      output_path: "dist/FinAppletWXExt-#{version}.zip"
    )

    # zipFileName ="FinAppletWXExt-#{version}.zip"
    # path=Dir.pwd
    # sh("coscli cp #{path}/../dist/#{zipFileName} cos://static-1251849568/finchat/sdk/#{zipFileName} --meta=x-cos-meta-build-type:release")
  
  if isUploadScp
    # scp(
    #   host: "192.168.0.35",
    #   username: "finchat",
    #   password: "abcd@@123",
    #   upload: {
    #     src: "dist/FinAppletWXExt-#{version}.zip",
    #     dst: "/data/ci/app/html/finchat/sdk"
    #   }
    # )
    # 原命令保留注释
    # sh("sshpass -p 'abcd@@123' scp ../dist/FinAppletWXExt-#{version}.zip finchat@192.168.0.35:/data/ci/app/html/finchat/sdk")
    # 使用重试脚本上传
    sh("#{SCP_RETRY_SCRIPT} ../dist/FinAppletWXExt-#{version}.zip finchat@192.168.0.35:/data/ci/app/html/finchat/sdk")
    handleSPM("../dist/FinAppletWXExt-#{version}.zip", version)
  end


  end

  lane :dev do |options|
    
    #version = sh("git describe --abbrev=0 --tags | tr -d '\\n' | tr -d '\\t'")
    version = ENV["version"]
    createReport = options[:createReport]
    isUploadScp = ENV['isUploadScp']

    # 增加build版本号
    #increment_build_number
    #set_info_plist_value(path: './FinAppletWXExt/Info.plist', key: 'CFBundleShortVersionString', value: "#{version}")
    
    # 编译代码
    xcodebuild(
      workspace: "FinAppletWXExt.xcworkspace",
      scheme: "FinAppletWXExt",
      xcargs: "-sdk iphoneos",
      configuration: "Release",
      clean: true,
      derivedDataPath: "./build",
      build: true
    )
    sh("mkdir -p ../dist/Release")
    sh("cp","-r", "../build/Build/Products/Release-iphoneos/FinAppletWXExt.framework", "../dist/Release/FinAppletWXExt.framework")

    xcodebuild(
      workspace: "FinAppletWXExt.xcworkspace",
      scheme: "FinAppletWXExt",
      xcargs: "-sdk iphonesimulator -arch arm64 -arch x86_64",
      configuration: "Release",
      clean: true,
      derivedDataPath: "./build",
      build: true
    )

    sh("xcodebuild -create-xcframework -framework ../dist/Release/FinAppletWXExt.framework -framework ../build/Build/Products/Release-iphonesimulator/FinAppletWXExt.framework -output ../dist/Release/FinAppletWXExt.xcframework")

    zip(
      path: "dist/Release/FinAppletWXExt.xcframework",
      output_path: "dist/FinAppletWXExt-#{version}.zip"
    )

    # zipFileName ="FinAppletWXExt-dev-#{version}.zip"
    # path=Dir.pwd
    # sh("coscli cp #{path}/../dist/#{zipFileName} cos://static-1251849568/finchat/sdk/#{zipFileName} --meta=x-cos-meta-build-type:release")
  
  if isUploadScp
    # scp(
    #   host: "192.168.0.35",
    #   username: "finchat",
    #   password: "abcd@@123",
    #   upload: {
    #     src: "dist/FinAppletWXExt-#{version}.zip",
    #     dst: "/data/ci/app/html/finchat/sdk"
    #   }
    # )
    # 原命令保留注释
    # sh("sshpass -p 'abcd@@123' scp ../dist/FinAppletWXExt-#{version}.zip finchat@192.168.0.35:/data/ci/app/html/finchat/sdk")
    # 使用重试脚本上传
    sh("#{SCP_RETRY_SCRIPT} ../dist/FinAppletWXExt-#{version}.zip finchat@192.168.0.35:/data/ci/app/html/finchat/sdk")
    handleSPM("../dist/FinAppletWXExt-#{version}.zip", version)
  end


  end


end
